# Modified from https://github.com/Interbotix/widowx_arm/blob/master/widowx_arm_controller/config/arm.yaml

port: /dev/ttyUSB0
read_rate: 50
write_rate: 50

joints: {
    joint_1: {id: 1, ticks: 4096, range: 360.0, max_speed: 100.0},
    joint_2: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0},
    joint_3: {id: 3, ticks: 4096, range: 360.0, max_speed: 100.0, invert: true},
    joint_4: {id: 4, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 100.0, invert: true},
    joint_5: {id: 5, ticks: 1024, range: 300.0, max_speed: 100.0, min_angle: -150.0, max_angle: 150.0},
    gripper_revolute_joint: {id: 6, ticks: 1024, range: 300.0, max_speed: 100.0, min_angle: 0.0, max_angle: 149.0, invert: true},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [joint_1, joint_2, joint_3, joint_4, joint_5, gripper_revolute_joint]},
}
